### ISSUE TITLE
Dialog/Verzeichnis-Setting wird bei Bibliothek-aufruf nicht übernommen

### ISSUE THREAD

**Issue by merlux** [lastship/script.module.lastship#17]
Wenn man einen Film in die Bibliothek exportiert und von dort aufruft, wird die Hoster-Liste als Dialog angezeigt, auch wenn in den Settings "Verzeichnis" eingestellt ist.

**Comment by lastship** [comment]
Das ist soweit ich weiß durch Kodi bedingt.Bedeutet es liegt an Kodi, da in der Bibliothek nur Dialog angezeigt werden kann

**Comment by merlux** [comment]
hab ich schon fast befürchtet...

**Comment by lastship** [comment]
thema schließen?

**Comment by merlux** [comment]
Hmmm... Ja, ich glaub da kann man nix machen...
