### ISSUE TITLE
Personensuche ohne Fehlermeldung

### ISSUE THREAD

**Issue by merlux** [lastship/script.module.lastship#5]
Wenn man nach Filmen oder Serien sucht, bei denen kein Eintrag gefunden wird, erscheint eine entsprechende Meldung.

Sucht man allerdings nach einer Person (Serie oder Film), und es wird keine gefunden, erscheint nichts.

Eventuell das try/catch [hier](https://github.com/lastship/script.module.lastship/blob/nightly/lib/resources/lib/indexers/movies.py#L244) z.B. weglassen?

**Comment by lastship** [comment]
Kannst du mal bitte ein Beispiel nennen

**Comment by merlux** [comment]
Ist mit merge #22 gefixt.
